COLUMNS_TO_READ = [
    "ID_CUSTOMER", "COUNTRY", "COB_DATE", "CONTRACT_START_DATE",
    "ID_CONTRACT", "VEHICLE_ID", "ID_QUOTATION",
    "GROUP_RATING", "COUNTERPARTY_RATING", "CLS_GROUP_RATING",
    "ARRS_BTWN_0_30D", "ARRS_BTWN_31_60D", "ARRS_BTWN_61_90D",
    "ARRS_BTWN_91_180D", "ARRS_BTWN_181_270D", "ARRS_MORE_270D",
]
