COLUMNS_TO_READ = [
    'ID_CONTRACT', 'VEHICLE_ID', 'ID_QUOTATION',
    'COB_DATE','COUNTRY', 'NOVA_ASSET_STATUS', 'BIKE_OR_CAR', 'CLS_VEHICLE_TYPE','BRAND_UPDATE', 'OEM_UPDATE', 'POWER_CATEGORY', 'VA_CO2_EMSS_REAL',
]
